# The build command and publish directory
[build]
  command = "npx @11ty/eleventy"
  publish = "_site"

# Functions configuration
[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"

# Schedule the function to run daily
[functions.fetch-legislation]
  schedule = "@daily"

# Caching policy for static assets (e.g., images, CSS)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Caching policy for HTML pages
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirects for the proxy and clean URLs
[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/foundation"
  to = "/foundation.html"
  status = 200

[[redirects]]
  from = "/network"
  to = "/network.html"
  status = 200

[[redirects]]
  from = "/playbook"
  to = "/playbook.html"
  status = 200

[[redirects]]
  from = "/atlas"
  to = "/atlas.html"
  status = 200

[[redirects]]
  from = "/data"
  to = "/data.html"
  status = 200
