backend:
  name: git-gateway
  branch: main # Or master, depending on your default branch name

# This line can be commented out to enable a publication workflow (drafts, etc.)
# publish_mode: editorial_workflow

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "reports"
    label: "State Reports"
    folder: "reports"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "html-frontmatter" # This tells the CMS to look for HTML with a body
    fields:
      # We don't need title or date fields, as they are part of the HTML file itself.
      # The "body" field will target the main content of your HTML files.
      - {label: "Report Content", name: "body", widget: "html"}
    editor:
      preview: false
