backend:
  name: git-gateway
  branch: main # Or master, depending on your default branch name

# This line enables the draft -> review -> approve workflow
publish_mode: editorial_workflow

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "reports"
    label: "State Reports"
    folder: "reports"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "html-frontmatter"
    fields:
      - {label: "Report Content", name: "body", widget: "html"}
    editor:
      preview: false
