name: Deploy Eleventy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    # IMPORTANT: Ensure this matches your repository's default branch name (e.g., main or master)
    branches: [ main ]

  # Allows manual triggering from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, cancelling previous runs
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a modern, stable Node.js version
          cache: 'npm'

      - name: Install dependencies
        # npm ci ensures a clean install based on package-lock.json
        run: npm ci

      - name: Build with Eleventy
        # This runs the 'npm run build' script defined in package.json
        run: npm run build
        # NOTE: The build process includes 'build:data' (update-legislation.js).
        # As seen in previous Netlify logs, this step likely requires the LEGISCAN_API_KEY.
        # You must add this key to your GitHub Repository Secrets (Settings -> Secrets and variables -> Actions).
        # env:
        #   LEGISCAN_API_KEY: ${{ secrets.LEGISCAN_API_KEY }}

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the Eleventy output directory
          path: './_site'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
